spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: org.postgresql.Driver
#    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/Persons?serverTimezone=UTC&useSSL=false
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
